<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_form_alter().
 */
function fred_form_alter(&$form, FormStateInterface $form_state, $form_id) {
 
  if ($form_id === 'user_login_form') {
   
     // Textfield.
    $form['name'] = [
      '#type' => 'textfield',
      '#title' => 'Please enter your name',
      '#size' => 60,
      '#maxlength' => 128,
      
    ];

     // Radios.
    $form['settings']['active'] = [
      '#type' => 'radios',
      '#title' => 'Poll status',
      '#options' => [0 => 'Closed', 1 => 'Active'],
      '#description' => 'Radios', 
       
    ];


    $form['#validate'][] = 'fred_custom_validate';
    // Add a custom submit handler to spit out the form array
    $form['#submit'][]  = 'fred_custom_submit_handler';
  }

}
  

/**
* Implements hook_theme() to add the template definition.
**/

function fred_theme($existing, $type, $theme, $path) {
  return [
    'my_template' => [
      'variables' => ['test_var' => NULL],
    ],
  ];
}

  





// implements  hook_block_view_BASE_BLOCK_ID_alter. Checking the label to verify if
// it is the tool menu block, and then change the title... 
function fred_block_view_system_menu_block_alter(array &$build, BlockPluginInterface $block) {
  if($build['#configuration']['label']  = "Tools"){
    $build['#configuration']['label']  = "Fish";
  } 
  
}



// output the form 
function fred_custom_submit_handler(&$form, FormStateInterface $form_state) {
ksm($form['settings']['active']);
}


function fred_custom_validate(array &$form, FormStateInterface $form_state) {

      if (strlen($form_state->getValue('name')) < 3) {
        $form_state->setErrorByName('name', 'The name is too short. Please enter a full name.');
      }
  
      if (!$form_state->getValue('active')) { 
        $form_state->setErrorByName('active', 'The poll must be active');
      }

}